language: c
dist: bionic
sudo: false

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev

before_install:

before_script:
  - export CPPFLAGS='-I/usr/include -I/usr/local/include'
  - export LDFLAGS='-L/usr/lib -L/usr/local/lib'
  - pwd
  - wget https://support.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.gz
  - tar zxf hdf-4.2.13.tar.gz
  - cd hdf-4.2.13
  - ./configure --disable-netcdf --prefix=/usr/local
  - make all 
  - sudo make install clean
  - cd ..
  - wget https://observer.gsfc.nasa.gov/ftp/edhs/hdfeos/latest_release/HDF-EOS2.20v1.00.tar.Z
  - tar zxf HDF-EOS2.20v1.00.tar.Z
  - cd hdfeos
  - ./configure  --enable-install-include --prefix=/usr/local
  - make
  - sudo make install
  - cd ..
  - wget https://github.com/captainkirk99/STARE/archive/0.11.3-beta.tar.gz
  - tar zxf 0.11.3-beta.tar.gz
  - cd STARE-0.11.3-beta/
  - mkdir build
  - cd build
  - cmake ..
  - make all
  - sudo make install
  - cd ../..
  - pwd
  - ls -l
  - ls -l /usr/local/lib
env:
  global:
    - CPPFLAGS='-I/usr/include -I/usr/local/include'
    - LDFLAGS='-L/usr/lib -L/usr/local/lib'
  
script:
  - export CFLAGS='-fsanitize=address'
  - autoreconf -i
  - ./configure --enable-docs
  - make -j distcheck
  - make -j distclean

