name: Autotools build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PWD_DIR: /home/runner
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/hdf4/include -I/home/runner/stare/include -I/home/runner/hdfeos2/include"
      LDFLAGS: "-L/home/runner/hdf4/lib -L/home/runner/stare/lib -L/home/runner/hdfeos2/lib"
        
    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev
    - name: cache-hdf4
      id: cache-hdf4
      uses: actions/cache@v2
      with:
        path: ~/hdf4
        key: pfunit-${{ runner.os }}-4.2.13

    - name: build-hdf4
      if: steps.cache-hdf4.outputs.cache-hit != 'true'
      run: |
        set -x
        pushd ~
        echo $HOME
        pwd
        echo $CPPFLAGS
        echo $LDFLAGS
        popd
        wget https://support.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.gz &> /dev/null
        tar zxf hdf-4.2.13.tar.gz
        cd hdf-4.2.13
        ./configure --disable-netcdf --prefix=${PWD_DIR}/hdf4
        make all 
        sudo make install clean
        cd ..
    - name: HDF-EOS2 setup
      run: |
        set -x
        wget https://observer.gsfc.nasa.gov/ftp/edhs/hdfeos/latest_release/HDF-EOS2.20v1.00.tar.Z  &> /dev/null
        tar zxf HDF-EOS2.20v1.00.tar.Z
        cd hdfeos
        ./configure  --enable-install-include --prefix=${PWD_DIR}/hdfeos2
        make
        sudo make install
        cd ..
    - name: STARE setup
      run: |
        set -x
        wget https://github.com/SpatioTemporal/STARE/archive/0.15.6-beta.tar.gz  &> /dev/null
        tar zxf 0.15.6-beta.tar.gz
        cd STARE-0.15.6-beta/
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/stare ..
        make all
        sudo make install
        cd ../..

        
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck


